import Link from "next/link";
import { getArticlesData } from "@/lib/articles";
import { getAllCases } from "@/lib/data";
import type { Article } from "@/types";

export const metadata = {
  title: "Analysis & Opinions · Supreme Court Tracker",
  description:
    "Supreme Court analysis and commentary from SCOTUSblog, The New York Times, The Atlantic, The New Yorker, and more.",
};

export default function AnalysisPage() {
  const data = getArticlesData();
  const allCases = getAllCases();
  const caseMap = new Map(allCases.map((c) => [c.slug, c.title]));

  return (
    <main className="min-h-screen bg-ft-paper">
      <header className="bg-ft-pink pt-10 px-6 pb-6">
        <div className="max-w-4xl mx-auto">
          <Link
            href="/"
            className="text-sm text-gray-600 hover:text-gray-900 hover:underline"
          >
            &larr; Supreme Court Tracker
          </Link>
          <h1
            className="mt-4 text-3xl sm:text-4xl font-bold text-gray-900 tracking-tight"
            style={{ fontFamily: "Graphika81, Georgia, serif" }}
          >
            Analysis &amp; Opinions
          </h1>
          <p className="mt-2 text-sm text-gray-600 max-w-2xl">
            Supreme Court coverage from SCOTUSblog, The New York Times, The
            Washington Post, The Atlantic, The New Yorker, and more. Summaries
            generated by Claude; click any title to read the full article.
          </p>
        </div>
      </header>

      <section className="max-w-4xl mx-auto px-6 py-10">
        {data && data.articles.length > 0 ? (
          <div className="space-y-6">
            {data.articles.map((article) => (
              <ArticleCard
                key={article.id}
                article={article}
                caseMap={caseMap}
              />
            ))}
          </div>
        ) : (
          <p className="text-sm text-gray-400 italic">
            No articles yet — run{" "}
            <code className="text-xs bg-gray-100 px-1 py-0.5 rounded">
              npx tsx scripts/fetch-analysis-articles.ts
            </code>{" "}
            to populate.
          </p>
        )}
      </section>
    </main>
  );
}

function ArticleCard({
  article,
  caseMap,
}: {
  article: Article;
  caseMap: Map<string, string>;
}) {
  return (
    <div className="bg-white rounded-lg border border-gray-200 p-5 space-y-3">
      <div className="flex items-center gap-2 text-xs text-gray-500">
        <span className="bg-gray-100 px-2 py-0.5 rounded font-medium text-gray-700">
          {article.source}
        </span>
        <span>{article.publishedAt}</span>
      </div>

      <a
        href={article.url}
        target="_blank"
        rel="noopener noreferrer"
        className="block text-base font-semibold text-gray-900 hover:text-blue-700 hover:underline leading-snug"
      >
        {article.title} ↗
      </a>

      <p className="text-sm text-gray-600 leading-relaxed">{article.summary}</p>

      {article.relatedCaseSlugs.length > 0 && (
        <div className="flex flex-wrap items-center gap-2 text-xs pt-1">
          <span className="text-gray-400 font-medium">Related:</span>
          {article.relatedCaseSlugs.map((slug) => {
            const title = caseMap.get(slug);
            if (!title) return null;
            return (
              <Link
                key={slug}
                href={`/cases/${slug}`}
                className="text-blue-600 hover:underline"
              >
                {title} →
              </Link>
            );
          })}
        </div>
      )}
    </div>
  );
}
