import Link from "next/link";
import { getArticlesData } from "@/lib/articles";
import { getAllCases } from "@/lib/data";
import type { Article } from "@/types";

export const metadata = {
  title: "Analysis & Opinions · Supreme Court Tracker",
  description:
    "Supreme Court analysis and commentary from SCOTUSblog, The New York Times, The Atlantic, The New Yorker, and more.",
};

export default function AnalysisPage() {
  const data = getArticlesData();
  const allCases = getAllCases();
  const caseMap = new Map(allCases.map((c) => [c.slug, c.title]));

  return (
    <main className="min-h-screen bg-[var(--cream)]">
      <header className="bg-[var(--cream)] pt-10 px-6 pb-6">
        <div className="max-w-4xl mx-auto">
          <Link
            href="/"
            className="text-[var(--warm-gray)] hover:text-[var(--rust)] transition-colors"
            style={{ fontFamily: "'DM Sans', sans-serif", fontWeight: 500, fontSize: "12px", textTransform: "uppercase", letterSpacing: "0.08em" }}
          >
            &larr; Supreme Court Tracker
          </Link>
          <h1
            className="mt-4 text-3xl sm:text-4xl font-bold text-[var(--charcoal)] tracking-tight"
            style={{ fontFamily: "'Playfair Display', Georgia, serif" }}
          >
            Analysis &amp; Opinions
          </h1>
          <p className="mt-2 text-[var(--warm-gray)] max-w-2xl" style={{ fontFamily: "'Lora', Georgia, serif", fontSize: "15px" }}>
            Supreme Court coverage from SCOTUSblog, The New York Times, The
            Washington Post, The Atlantic, The New Yorker, and more. Summaries
            generated by Claude; click any title to read the full article.
          </p>
        </div>
      </header>

      <section className="max-w-4xl mx-auto px-6 py-10">
        {data && data.articles.length > 0 ? (
          <div className="space-y-6">
            {data.articles.map((article) => (
              <ArticleCard
                key={article.id}
                article={article}
                caseMap={caseMap}
              />
            ))}
          </div>
        ) : (
          <p className="text-[var(--warm-gray)] text-sm italic" style={{ fontFamily: "'Lora', Georgia, serif" }}>
            No articles yet — run{" "}
            <code
              className="bg-[var(--ivory)] px-1 py-0.5 rounded border border-[var(--tan)]"
              style={{ fontFamily: "'DM Mono', monospace", fontSize: "12px" }}
            >
              npx tsx scripts/fetch-analysis-articles.ts
            </code>{" "}
            to populate.
          </p>
        )}
      </section>
    </main>
  );
}

function ArticleCard({
  article,
  caseMap,
}: {
  article: Article;
  caseMap: Map<string, string>;
}) {
  return (
    <div className="bg-[var(--ivory)] rounded-lg border border-[var(--tan)] p-5 space-y-3 shadow-[0_1px_3px_rgba(0,0,0,0.06)]">
      <div className="flex items-center gap-2" style={{ fontFamily: "'DM Mono', monospace", fontSize: "11px" }}>
        <span
          className="bg-[var(--cream)] px-2 py-0.5 rounded border border-[var(--tan)] text-[var(--charcoal)]"
          style={{ fontFamily: "'DM Sans', sans-serif", fontWeight: 500, fontSize: "10px", textTransform: "uppercase" }}
        >
          {article.source}
        </span>
        {article.author && <span className="text-[var(--warm-gray)]">{article.author}</span>}
        <span className="text-[var(--warm-gray)]">{article.publishedAt}</span>
      </div>

      <a
        href={article.url}
        target="_blank"
        rel="noopener noreferrer"
        className="block text-[var(--charcoal)] hover:text-[var(--rust)] leading-snug transition-colors"
        style={{ fontFamily: "'Playfair Display', Georgia, serif", fontWeight: 600, fontSize: "18px" }}
      >
        {article.title}
      </a>

      <p className="text-[var(--charcoal)] leading-relaxed" style={{ fontFamily: "'Lora', Georgia, serif", fontSize: "14px" }}>{article.summary}</p>

      {article.relatedCaseSlugs.length > 0 && (
        <div className="flex flex-wrap items-center gap-2 pt-1">
          <span className="text-[var(--warm-gray)]" style={{ fontFamily: "'DM Sans', sans-serif", fontWeight: 500, fontSize: "10px", textTransform: "uppercase" }}>Related:</span>
          {article.relatedCaseSlugs.map((slug) => {
            const title = caseMap.get(slug);
            if (!title) return null;
            return (
              <Link
                key={slug}
                href={`/cases/${slug}`}
                className="text-[var(--rust)] hover:underline"
                style={{ fontFamily: "'DM Mono', monospace", fontSize: "11px" }}
              >
                {title}
              </Link>
            );
          })}
        </div>
      )}
    </div>
  );
}
